version: '3.8'
services:
  vtep:
    image: ghcr.io/razelighter777/vtep
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.forwarding: 1
      net.ipv4.conf.default.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
    build:
      context: .
      dockerfile: vtep/Dockerfile
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    ports:
      - "53:53/udp"
      - "2222:2222/tcp"  # Expose SSH port for VTEP
    depends_on:
      - redis
      - carve-api
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      - PUID=1000
      - PGID=1000
      - SSH_PORT=2222
      - PASSWORD_ACCESS=1
      - USER_NAME=carve
      - USER_PASSWORD=carve1234
    network_mode: service:vtep
  vxlan-sidecar-team1-web:
    image: ghcr.io/razelighter777/vxlan-sidecar
    cap_add:
      - NET_ADMIN
    ports:
      - "5901:5900"
      - "5700:5700"
    build:
      context: .
      dockerfile: vxlan-sidecar/Dockerfile
    environment:
      - TEAM_NAME=team1
      - COMPETITION_NAME=CarveCTF
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
      - vtep
  team1-web:
    image: ghcr.io/razelighter777/qemu-box
    build:
      context: .
      dockerfile: qemu-box/Dockerfile
    volumes:
      - ./competition.yaml:/config/competition.yaml:ro
      - ./disks/:/disks
    environment:
      - TEAM_NAME=team1
      - BOX_NAME=web
      - COMPETITION_NAME=CarveCTF
      - RUST_LOG=debug
    depends_on:
      - vxlan-sidecar-team1-web
      - carve-dnsmasq
    network_mode: service:vxlan-sidecar-team1-web
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
  vxlan-sidecar-team2-web:
    image: ghcr.io/razelighter777/vxlan-sidecar
    cap_add:
      - NET_ADMIN
    ports:
      - "5902:5900"
      - "5701:5700"
    environment:
      - TEAM_NAME=team2
      - COMPETITION_NAME=CarveCTF
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
      - vtep
  team2-web:
    image: ghcr.io/razelighter777/qemu-box
    volumes:
      - ./competition.yaml:/config/competition.yaml:ro
      - ./disks:/disks
    environment:
      - TEAM_NAME=team2
      - BOX_NAME=web
      - COMPETITION_NAME=CarveCTF
      - RUST_LOG=debug
    depends_on:
      - vxlan-sidecar-team2-web
      - carve-dnsmasq
    network_mode: service:vxlan-sidecar-team2-web
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm

  canary:
    image: ghcr.io/razelighter777/canary
    build:
      context: .
      dockerfile: canary/Dockerfile
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
      - carve-dnsmasq
    network_mode: service:vtep
  carve-web:
    image: ghcr.io/razelighter777/web
    build:
      context: .
      dockerfile: carve-web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  carve-dnsmasq:
    image: ghcr.io/razelighter777/carve-dnsmasq
    build:
      context: .
      dockerfile: carve-dnsmasq/Dockerfile
    environment:
      - COMPETITION_NAME=CarveCTF
    volumes:
      - ./competition.yaml:/config/competition.yaml:ro
    depends_on:
      - vtep
    cap_add:
      - NET_ADMIN
    network_mode: service:vtep
  carve-api:
    image: ghcr.io/razelighter777/carve-api
    build:
      context: .
      dockerfile: carve-api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - COMPETITION_NAME=CarveCTF
      # for testing purposes, use a fixed secret key
      # in production, you should generate a secure key
      # and store it securely, e.g., in an environment variable or a secret management system
      - SECRET_KEY=82eb0275e23e5f043e85762e798fd9d61b1040ecdba15d001eb52f416e08ef3e
      - OAUTH2_CLIENT_ID=MerToF4xtp7PwRrumFd4kdOf5ldu1OcmNFaqyZ9p
      - OAUTH2_CLIENT_SECRET=CBIqtzJu4jLelR92PU1W7eao0i83Wldaz5BDfWVJljcesUHaThp5MM1xzVQKUFizTxgjmxuc81YkXZawKsb2tCLltlUuRzaGUkhtdaeIbp5eT7ct5M53Abix7paxQJtK
      - OAUTH2_REDIRECT_URL=https://carve.prizrak.me/api/v1/oauth2/callback
      - OAUTH2_TOKEN_URL=https://authentik.prizrak.me/application/o/token/
      - OAUTH2_AUTH_URL=https://authentik.prizrak.me/application/o/authorize/
      - OAUTH2_USERINFO_URL=https://authentik.prizrak.me/application/o/userinfo/
    volumes:
      - ./competition.yaml:/config/competition.yaml:ro
    depends_on:
      - redis
  carve-novnc-nginx:
    image: ghcr.io/razelighter777/carve-novnc-nginx
    build:
      context: .
      dockerfile: carve-novnc-nginx/Dockerfile
    ports:
      - "6080:80"
    depends_on:
      - carve-web
      - carve-api
      - redis
      - team1-web
    volumes:
      - ./competition.yaml:/config/competition.yaml:ro
  qemu-nbd:
    image: ghcr.io/razelighter777/qemu-nbd
    build:
      context: .
      dockerfile: qemu-nbd/Dockerfile
    environment:
      - DOWNLOAD_IMAGE=https://dl-cdn.alpinelinux.org/alpine/v3.22/releases/cloud/nocloud_alpine-3.22.0-x86_64-bios-cloudinit-r0.qcow2
    ports:
      - "10809:10809"