version: '3.8'
services:
  vtep:
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.forwarding: 1
      net.ipv4.conf.default.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
    build:
      context: .
      dockerfile: vtep/Dockerfile
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    environment:
      - VXLAN_ID=1001
      - CIDR=10.10.0.0/16
    depends_on:
      - redis
  vxlan-sidecar:
    cap_add:
      - NET_ADMIN
    build:
      context: .
      dockerfile: vxlan-sidecar/Dockerfile
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
  canary:
    build:
      context: .
      dockerfile: canary/Dockerfile
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
