version: '3.8'
services:
  vtep:
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.forwarding: 1
      net.ipv4.conf.default.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
      net.ipv6.conf.default.forwarding: 1
    build:
      context: .
      dockerfile: vtep/Dockerfile
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    environment:
      - VXLAN_ID=1001
      - CIDR=10.10.0.0/16
    depends_on:
      - redis
  vxlan-sidecar-team1-web:
    cap_add:
      - NET_ADMIN
    ports:
      - "5900:5900"
    build:
      context: .
      dockerfile: vxlan-sidecar/Dockerfile
    environment:
      - TEAM_NAME=team1
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
      - vtep
  team1-web:
    build:
      context: .
      dockerfile: qemu-box/Dockerfile
    volumes:
      - ./competition.yaml:/config/competition.yaml:ro
      - ./disks/ubuntu/ubuntu-24.04-nocloud.qcow2:/disk/ubuntu-24.04-nocloud.qcow2
    environment:
      - TEAM_NAME=team1
      - BOX_NAME=web
      - COMPETITION_NAME=defcon
    depends_on:
      - vxlan-sidecar-team1-web
    network_mode: service:vxlan-sidecar-team1-web
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm

  canary:
    build:
      context: .
      dockerfile: canary/Dockerfile
    volumes:
      - ./competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
  carve-web:
    build:
      context: .
      dockerfile: carve-web/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
