version: '3.8'
services:
  vtep:
    build:
      context: .
      dockerfile: vtep/Dockerfile
    volumes:
      - ./vtep/competition.yaml:/app/competition.yaml:ro
    environment:
      - VXLAN_ID=1001
      - CIDR=10.10.0.0/16
    depends_on:
      - redis
  vxlan-sidecar:
    build:
      context: .
      dockerfile: vxlan-sidecar/Dockerfile
    volumes:
      - ./vtep/competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
  canary:
    build:
      context: .
      dockerfile: canary/Dockerfile
    volumes:
      - ./vtep/competition.yaml:/app/competition.yaml:ro
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
