[package]
name = "carve-novnc-nginx"
version = "0.1.0"
edition = "2024"

[dependencies]
carve = { path = "../carve" }
tokio = { version = "1.46.1", features = ["full"] }


[[bin]]
name = "carve-novnc-nginx"
path = "src/main.rs"
