[project]
name = "carve-ansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.7.0",
    "dnspython>=2.7.0",
    "pyyaml>=6.0.2",
    "redis>=6.2.0",
]
