[package]
name = "vtep"
version = "0.1.0"
edition = "2024"

[dependencies]
carve = { path = "../carve" }
iptables = "0.5.3"
redis = "0.32.0"
actix-web = "4"
actix-rt = "2"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.98"

[[bin]]
name = "vtep"   
path = "src/main.rs"
