[package]
name = "vxlan-sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
carve = { path = "../carve" }
iptables = "0.5.3"
redis = "0.32.0"
rocket = { version = "0.5.0-rc.3", features = ["json"] }
tokio = { version = "1", features = ["full"] }