---
- name: Generate flag using carve-api
  hosts: localhost
  gather_facts: false
  vars:
    flag_check_name: "example_check"
    team_name: "example_team"
  tasks:
    - name: Call generate_flag API
      uri:
        url: "http://{{ api_host }}:{{ api_port }}{{ api_path }}?flagCheckName={{ flag_check_name }}&teamName={{ team_name }}"
        method: GET
        return_content: yes
        status_code: 200
        headers:
          Authorization: "Bearer {{ lookup('env', 'SECRET_KEY') }}"
      register: flag_response

    - name: Set flag variable
      set_fact:
        generated_flag: "{{ flag_response.json.flag }}"

    - name: Debug flag
      debug:
        var: generated_flag
