{{- range $team := .Values.competition.teams }}
  {{- range $box := $.Values.competition.boxes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carve-{{ $team.name }}-{{ $box.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carve-{{ $team.name }}-{{ $box.name }}
  template:
    metadata:
      labels:
        app: carve-{{ $team.name }}-{{ $box.name }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: qemu-box
          image: "{{ $.Values.images.qemuBox.repository }}:{{ $.Values.images.qemuBox.tag }}"
          imagePullPolicy: {{ $.Values.images.qemuBox.pullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TEAM_NAME
              value: {{ $team.name | quote }}
            - name: BOX_NAME
              value: {{ $box.name | quote }}
            - name: COMPETITION_NAME
              value: {{ $.Values.competition.name | quote }}
            - name: RUST_LOG
              value: debug
          volumeMounts:
            {{- if $.Values.persistence.disks.enabled }}
            - name: disks
              mountPath: /disks
              readOnly: true
            {{- end }}
            - name: state
              mountPath: /state
            - name: competition-config
              mountPath: /config/competition.yaml
              subPath: competition.yaml
              readOnly: true
            - name: dev-kvm
              mountPath: /dev/kvm
        - name: vxlan-sidecar
          image: "{{ $.Values.images.vxlanSidecar.repository }}:{{ $.Values.images.vxlanSidecar.tag }}"
          imagePullPolicy: {{ $.Values.images.vxlanSidecar.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: TEAM_NAME
              value: {{ $team.name | quote }}
            - name: COMPETITION_NAME
              value: {{ $.Values.competition.name | quote }}
            - name: BOX_NAME
              value: {{ $box.name | quote }}
          volumeMounts:
            - name: competition-config
              mountPath: /app/competition.yaml
              subPath: competition.yaml
              readOnly: true
            {{- if $.Values.persistence.disks.enabled }}
            - name: disks
              mountPath: /disks
              readOnly: true
            {{- end }}
      volumes:
        {{- if $.Values.persistence.disks.enabled }}
        - name: disks
          persistentVolumeClaim:
            claimName: disks-shared
        {{- end }}
        - name: state
          persistentVolumeClaim:
            claimName: state-{{ $team.name }}-{{ $box.name }}
        - name: competition-config
          configMap:
            name: competition-config
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
{{- end }}
{{- end }}
