apiVersion: v1
kind: Service
metadata:
  name: carve-network-dns
  labels:
    app: carve-network
spec:
  type: ClusterIP
  selector:
    app: carve-network
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: carve-network-ssh
  labels:
    app: carve-network
spec:
  type: ClusterIP
  selector:
    app: carve-network
  ports:
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 2222
