{{- range $team := .Values.competition.teams }}
  {{- range $box := $.Values.competition.boxes }}
---
apiVersion: v1
kind: Service
metadata:
  name: vxlan-sidecar-{{ $team.name }}-{{ $box.name }}
  labels:
    app: carve-{{ $team.name }}-{{ $box.name }}
spec:
  type: ClusterIP
  selector:
    app: carve-{{ $team.name }}-{{ $box.name }}
  ports:
    - name: vnc-console
      protocol: TCP
      port: 5700
      targetPort: 5700
    - name: xtermjs-websocket
      protocol: TCP
      port: 9999
      targetPort: 9999
    - name: vtep
      protocol: UDP
      port: 4789
      targetPort: 4789
{{- end }}
{{- end }}
