apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disks-shared
spec:
  accessModes: {{ toYaml .Values.persistence.disks.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.persistence.disks.size }}
  {{- if .Values.persistence.disks.storageClassName }}
  storageClassName: {{ .Values.persistence.disks.storageClassName }}
  {{- end }}
---
{{- range $team := .Values.competition.teams }}
  {{- range $box := $.Values.competition.boxes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: state-{{ $team.name }}-{{ $box.name }}
spec:
  accessModes: {{ toYaml $.Values.persistence.state.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ $.Values.persistence.state.size }}
  {{- if $.Values.persistence.state.storageClassName }}
  storageClassName: {{ $.Values.persistence.state.storageClassName }}
  {{- end }}
---
  {{- end }}
{{- end }}
