apiVersion: v1
kind: ConfigMap
metadata:
  name: competition-config
  labels:
    app: carve
    chart: carve
    heritage: Helm
    release: {{ .Release.Name }}
data:
  competition.yaml: |
    competitions: 
    -  {{- .Values.competition | toYaml | nindent 6 }}